# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewYorkTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
  # Pods for NewYorkTimes
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
pod 'Kingfisher'
  target 'NewYorkTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewYorkTimesUITests' do
    # Pods for testing
  end

end
